### ISSUE TITLE
ask if you want to save the file on exit

### ISSUE THREAD

**Issue by not-nef** [Futura-Py/notes#74]

**Comment by HuyHung1408** [comment]
Add an option to auto-save the file every time we close the app would be great?

**Comment by not-nef** [comment]
yeah i can add that too

**Comment by im-coder-lg** [comment]
Um what about CPU usage if that is enabled? It has to affect it right?

**Comment by not-nef** [comment]
no not at all, why do you ask?

**Comment by im-coder-lg** [comment]
Well, auto-save has to work on a timed basis, eg. 15 minutes after each save. It can be force-stopped by manual save, but mainly the time code could just keep looping, get my track? That could eat up memory and swap storage, right?

**Comment by not-nef** [comment]
nah, @HuyHung1408 meant that the program saves without asking when the program is closed. thats easy by just catching the window delete protocol

**Comment by im-coder-lg** [comment]
Oh, that way. For most of us, autosave means a periodic save of a file, that is immediately saved on closing or on a fixed timeframe or when the file is out of focus, ie. when I open up another file. This is a really good idea, however you must make it customisable to the users, right?

**Comment by not-nef** [comment]
my commit is from the future

![image](https://user-images.githubusercontent.com/83908932/209444018-c434a39e-1dca-4771-9ffc-f4342d944a2c.jpeg)

**Comment by im-coder-lg** [comment]
Well that is the weirdest thing I ever have seen, and I see a lot of weird things.

**Comment by im-coder-lg** [comment]
Looks like I need to look for a commit resistance haha

**Comment by sumeshir26** [comment]
lol is ur phone set to a different time than ur pc?

**Comment by not-nef** [comment]
actually no

**Comment by not-nef** [comment]
why should it be that would be confusing as hell

**Comment by im-coder-lg** [comment]
Well, what @sumeshir26 told was right. However, git commits are made with the date too, which could tell you stuff.
